/** Shared badges & outcome one-liners for shop grids (main shop + family hubs). */

export const SHOP_BADGE_MAP: Record<string, { label: string; color: string }> = {
  "combo-bundle": { label: "Best Value", color: "bg-amber-500/20 text-amber-300" },
  "complete-injector-bundle": { label: "Popular", color: "bg-sky-500/20 text-sky-300" },
  "med-spa-legal-startup-bundle": { label: "Essential", color: "bg-rose-500/20 text-rose-300" },
  "botox-consent-bundle": { label: "Top Rated", color: "bg-emerald-500/20 text-emerald-300" },
  "hipaa-compliance-kit": { label: "Required", color: "bg-red-500/20 text-red-300" },
  "injectors-playbook": { label: "Premium", color: "bg-amber-500/20 text-amber-300" },
  "new-injector-onboarding-kit": { label: "New", color: "bg-sky-500/20 text-sky-300" },
  "guidebook-category-strategy": { label: "Strategy", color: "bg-violet-500/20 text-violet-300" },
  "microblading-pmu-playbook": { label: "Premium", color: "bg-amber-500/20 text-amber-300" },
  "treatment-menu-signage-kit": { label: "New", color: "bg-sky-500/20 text-sky-300" },
  "aftercare-card-kit": { label: "Must Have", color: "bg-emerald-500/20 text-emerald-300" },
  "patient-communication-kit": { label: "New", color: "bg-sky-500/20 text-sky-300" },
  "medspa-social-media-system": { label: "Best Seller", color: "bg-emerald-500/20 text-emerald-300" },
  "medspa-content-strategy-system": { label: "New", color: "bg-sky-500/20 text-sky-300" },
  "hormone-therapy-playbook": { label: "New", color: "bg-violet-500/20 text-violet-300" },
  "peptide-therapy-playbook": { label: "Hot", color: "bg-orange-500/20 text-orange-300" },
  "google-domination-playbook": { label: "Hot", color: "bg-orange-500/20 text-orange-300" },
  "patient-loyalty-system": { label: "High ROI", color: "bg-emerald-500/20 text-emerald-300" },
  "botox-patient-journey-kit": { label: "Journey Kit", color: "bg-sky-500/20 text-sky-300" },
  "filler-patient-journey-kit": { label: "Journey Kit", color: "bg-sky-500/20 text-sky-300" },
  "glp1-patient-journey-kit": { label: "Journey Kit", color: "bg-sky-500/20 text-sky-300" },
  "iv-therapy-patient-journey-kit": { label: "Journey Kit", color: "bg-sky-500/20 text-sky-300" },
  "microneedling-patient-journey-kit": { label: "Journey Kit", color: "bg-sky-500/20 text-sky-300" },
  "chemical-peel-patient-journey-kit": { label: "Journey Kit", color: "bg-sky-500/20 text-sky-300" },
  "hormone-patient-journey-kit": { label: "Journey Kit", color: "bg-sky-500/20 text-sky-300" },
  "peptide-patient-journey-kit": { label: "Journey Kit", color: "bg-sky-500/20 text-sky-300" },
  "medical-disclaimer-system": { label: "Essential", color: "bg-red-500/20 text-red-300" },
  "diy-google-setup-kit": { label: "Best Value", color: "bg-emerald-500/20 text-emerald-300" },
  "botox-clinical-cheat-sheet": { label: "$10 Quick Ref", color: "bg-cyan-500/20 text-cyan-300" },
  "iv-therapy-clinical-cheat-sheet": { label: "$10 Quick Ref", color: "bg-cyan-500/20 text-cyan-300" },
  "peptide-therapy-clinical-cheat-sheet": { label: "$10 Quick Ref", color: "bg-cyan-500/20 text-cyan-300" },
  "hormone-therapy-clinical-cheat-sheet": { label: "$10 Quick Ref", color: "bg-cyan-500/20 text-cyan-300" },
  "glp1-clinical-cheat-sheet": { label: "$10 Quick Ref", color: "bg-cyan-500/20 text-cyan-300" },
  "dermal-filler-clinical-cheat-sheet": { label: "$10 Quick Ref", color: "bg-cyan-500/20 text-cyan-300" },
  "pellet-therapy-clinical-cheat-sheet": { label: "$10 Quick Ref", color: "bg-cyan-500/20 text-cyan-300" },
  "pharmaceutical-reference-cheat-sheet": { label: "$10 Quick Ref", color: "bg-cyan-500/20 text-cyan-300" },
  "olympia-iv-dosing-guide-cheat-sheet": { label: "$10 Quick Ref", color: "bg-cyan-500/20 text-cyan-300" },
  "lash-extensions-clinical-cheat-sheet": { label: "$10 Quick Ref", color: "bg-cyan-500/20 text-cyan-300" },
  "lash-lift-perm-clinical-cheat-sheet": { label: "$10 Quick Ref", color: "bg-cyan-500/20 text-cyan-300" },
  "brow-henna-clinical-cheat-sheet": { label: "$10 Quick Ref", color: "bg-cyan-500/20 text-cyan-300" },
  "waxing-clinical-cheat-sheet": { label: "$10 Quick Ref", color: "bg-cyan-500/20 text-cyan-300" },
  "ipl-laser-clinical-cheat-sheet": { label: "$10 Quick Ref", color: "bg-cyan-500/20 text-cyan-300" },
  "consent-botox-neurotoxins": { label: "$19 consent", color: "bg-rose-500/20 text-rose-300" },
  "consent-dermal-filler": { label: "$19 consent", color: "bg-rose-500/20 text-rose-300" },
  "consent-glp1-weight-loss": { label: "$19 consent", color: "bg-rose-500/20 text-rose-300" },
  "consent-hormone-therapy": { label: "$19 consent", color: "bg-rose-500/20 text-rose-300" },
  "consent-iv-im-therapy": { label: "$19 consent", color: "bg-rose-500/20 text-rose-300" },
  "consent-laser-ipl": { label: "$19 consent", color: "bg-rose-500/20 text-rose-300" },
  "consent-lash-extensions": { label: "$19 consent", color: "bg-rose-500/20 text-rose-300" },
  "consent-waxing": { label: "$19 consent", color: "bg-rose-500/20 text-rose-300" },
  "consent-microneedling-rf": { label: "$19 consent", color: "bg-rose-500/20 text-rose-300" },
  "consent-photography-hipaa": { label: "$19 consent", color: "bg-rose-500/20 text-rose-300" },
  "insurance-legal-compliance-guide": { label: "$47 · Guide", color: "bg-violet-500/20 text-violet-300" },
  "phase-2-business-bundle": { label: "$47 · Guide", color: "bg-violet-500/20 text-violet-300" },
  "difficult-client-scripts": { label: "$47 · Guide", color: "bg-violet-500/20 text-violet-300" },
  "before-after-photo-system": { label: "$47 · Guide", color: "bg-violet-500/20 text-violet-300" },
  "vendor-supplier-directory": { label: "$47 · Guide", color: "bg-violet-500/20 text-violet-300" },
  "31-day-social-media-content-calendar": { label: "$47 · Calendar", color: "bg-fuchsia-500/20 text-fuchsia-300" },
  "facial-anatomy-nurse-injector": {
    label: "Top pick · Most popular",
    color: "bg-emerald-500/20 text-emerald-300",
  },
  "npa-49-star-system": { label: "Best Seller", color: "bg-emerald-500/20 text-emerald-300" },
  "botox-social-bundle": { label: "Social pack", color: "bg-fuchsia-500/20 text-fuchsia-300" },
  "filler-social-bundle": { label: "Social pack", color: "bg-fuchsia-500/20 text-fuchsia-300" },
  "filler-consent-bundle": { label: "Full bundle", color: "bg-emerald-500/20 text-emerald-300" },
  "chemical-peel-consent-bundle": { label: "6 templates", color: "bg-rose-500/20 text-rose-300" },
  "microneedling-consent-bundle": { label: "6 templates", color: "bg-rose-500/20 text-rose-300" },
  "medspa-promo-pack": { label: "10 templates", color: "bg-fuchsia-500/20 text-fuchsia-300" },
  "myths-facts-injectors": { label: "10 templates", color: "bg-fuchsia-500/20 text-fuchsia-300" },
  "new-patient-membership-pack": { label: "10 templates", color: "bg-fuchsia-500/20 text-fuchsia-300" },
  "review-testimonial-pack": { label: "10 templates", color: "bg-fuchsia-500/20 text-fuchsia-300" },
  "seasonal-marketing-pack": { label: "10 templates", color: "bg-fuchsia-500/20 text-fuchsia-300" },
  "iv-story-templates": { label: "10 templates", color: "bg-purple-500/20 text-purple-300" },
  "glp1-story-templates": { label: "10 templates", color: "bg-orange-500/20 text-orange-300" },
  "weight-loss-kit": { label: "Full kit", color: "bg-orange-500/20 text-orange-300" },
  "iv-therapy-social-kit": { label: "Mega social", color: "bg-purple-500/20 text-purple-300" },
  "peptide-patient-guide": { label: "7 templates", color: "bg-violet-500/20 text-violet-300" },
  "peptide-canva-marketing-pack": { label: "Canva flagship", color: "bg-orange-500/20 text-orange-300" },
  "lash-aftercare-kit": { label: "Aftercare", color: "bg-emerald-500/20 text-emerald-300" },
  "medspa-startup-checklist": { label: "Checklist", color: "bg-sky-500/20 text-sky-300" },
};

export const SHOP_OUTCOME_MAP: Record<string, string> = {
  "combo-bundle": "Save 40% vs buying separately. Your complete marketing toolkit.",
  "complete-injector-bundle": "Post consistently for 3+ months without creating a single graphic.",
  "med-spa-legal-startup-bundle": "Open your doors legally. 34 templates your attorney will thank you for.",
  "botox-consent-bundle": "Protect your practice and look professional from day one.",
  "hipaa-compliance-kit": "Be audit-ready tomorrow. Not next month.",
  "injectors-playbook": "Ryan's exact consultation scripts, dosing protocols, and clinical systems — in your hands.",
  "new-injector-onboarding-kit": "Train your next injector in 30 days. Not 6 months of trial and error.",
  "guidebook-category-strategy": "Build a digital product business that earns while you sleep.",
  "microblading-pmu-playbook": "Run your PMU business like a clinic, not a side hustle.",
  "treatment-menu-signage-kit": "Your lobby looks professional in 10 minutes. Print and display.",
  "aftercare-card-kit": "Hand patients a card after every treatment. Fewer callbacks, better outcomes.",
  "patient-communication-kit": "Copy, paste, send. Every patient message you'll ever need.",
  "medspa-social-media-system": "90 days of content — done. Stop staring at a blank screen every Monday morning.",
  "medspa-content-strategy-system": "For established spas who post inconsistently. Every decision already made.",
  "hormone-therapy-playbook": "Add BHRT to your practice. Screening, protocols, vendors, consent — the complete system.",
  "peptide-therapy-playbook": "The hottest niche in wellness. BPC-157, semaglutide, NAD+ — protocols your patients are already asking about.",
  "google-domination-playbook": "87% of patients Google you before booking. This playbook makes sure they find YOU.",
  "patient-loyalty-system": "One rebooking script pays for this 10x over. Turn one-time patients into lifetime revenue.",
  "botox-patient-journey-kit": "Every touchpoint from first inquiry to rebooking. Hand this to your front desk and never miss a step.",
  "filler-patient-journey-kit": "Swelling timeline, dissolving options, day-by-day recovery — the filler patient's complete guide.",
  "glp1-patient-journey-kit": "Lab requirements to monthly check-ins. Manage nausea, set expectations, keep patients on track.",
  "iv-therapy-patient-journey-kit": "Pre-hydration, during-treatment expectations, NAD+ recovery — the fastest post-care in the series.",
  "microneedling-patient-journey-kit": "Day 1 red, Day 3 sandpaper, Day 7 glowing. Give patients the roadmap so they don't panic.",
  "chemical-peel-patient-journey-kit": "Peeling timeline days 1-7, sun avoidance protocol, Fitzpatrick screening — the complete peel guide.",
  "hormone-patient-journey-kit": "Labs, delivery method consent, symptom tracking, monthly follow-up — the BHRT patient's complete journey.",
  "peptide-patient-journey-kit": "Reconstitution, injection technique, storage, goal-based protocols — everything your peptide patient needs.",
  "medical-disclaimer-system": "Selling clinical content without disclaimers? That's a lawsuit waiting to happen. Fix it in 10 minutes.",
  "diy-google-setup-kit": "Everything an agency charges $797 for — in one $297 download. Set up your own Google presence.",
  "botox-clinical-cheat-sheet": "Landmarks, dosing cues, and complication reminders at a glance — keep it at the chair.",
  "iv-therapy-clinical-cheat-sheet": "Drip math, additives, and red-flag cues without flipping through a full IV manual.",
  "peptide-therapy-clinical-cheat-sheet": "Reconstitution, screening, and documentation prompts — built for busy peptide visits.",
  "hormone-therapy-clinical-cheat-sheet": "BHRT labs, delivery methods, and follow-up rhythm on one sheet at the chair.",
  "glp1-clinical-cheat-sheet": "Titration, side effects, and escalation cues for GLP-1 visits — fast and consistent.",
  "dermal-filler-clinical-cheat-sheet": "Depth, anatomy, reversal, and complication reminders — filler confidence in one glance.",
  "pellet-therapy-clinical-cheat-sheet": "Insertion, dosing rhythm, and follow-up cues for pellet visits — keep it at the chair.",
  "pharmaceutical-reference-cheat-sheet": "High-yield med-class reminders and documentation prompts without digging through references.",
  "olympia-iv-dosing-guide-cheat-sheet": "Olympia-style IV menu dosing, bags, and additives in one glance for the IV suite.",
  "lash-extensions-clinical-cheat-sheet": "Isolation, adhesive, fills, and allergy cues at a glance — keep it at the lash bed.",
  "lash-lift-perm-clinical-cheat-sheet": "Processing, patch tests, and contraindications for lift and perm without flipping through a manual.",
  "brow-henna-clinical-cheat-sheet": "Prep, develop timing, and aftercare prompts for henna and tint services between clients.",
  "waxing-clinical-cheat-sheet": "Temperature, technique, and contraindication checks for consistent wax room flow.",
  "ipl-laser-clinical-cheat-sheet": "Settings, skin-type cues, and post-treatment reminders for IPL and laser visits.",
  "consent-botox-neurotoxins": "Standalone neurotoxin informed consent — risks, alternatives, and signatures without the full bundle.",
  "consent-dermal-filler": "Single filler consent covering vascular risk, dissolution options, and patient acknowledgments.",
  "consent-glp1-weight-loss": "GLP-1 program consent for side effects, monitoring, and patient signatures.",
  "consent-hormone-therapy": "BHRT/TRT consent language for hormone services — ready to brand and print.",
  "consent-iv-im-therapy": "IV and IM therapy consent for your infusion suite documentation.",
  "consent-laser-ipl": "Laser and IPL treatment consent with device-appropriate disclosures.",
  "consent-lash-extensions": "Lash extension consent — adhesive, allergies, fills, and aftercare in one form.",
  "consent-waxing": "Professional waxing consent for contraindications, skin integrity, and post-care.",
  "consent-microneedling-rf": "Microneedling and RF consent — series expectations, risks, and aftercare.",
  "consent-photography-hipaa": "Photo authorization with tiered use options and HIPAA-aligned language.",
  "insurance-legal-compliance-guide":
    "Danielle Alcala's 10-year framework for insurance, legal, and compliance — disclaimers on the cover and every page footer. Not legal advice; consult an attorney.",
  "phase-2-business-bundle": "Next-phase systems for an aesthetic business that has outgrown startup mode — priorities, structure, and momentum.",
  "difficult-client-scripts": "Scripts and framing for tense moments — complaints, refunds, boundaries — so your team sounds calm and consistent.",
  "before-after-photo-system": "Repeatable before/after workflow — consistency, storage, and alignment with your consent and marketing rules.",
  "vendor-supplier-directory": "Track vendors, reps, and reorders in one place — a directory framework you fill with your real suppliers.",
  "31-day-social-media-content-calendar":
    "A full month of med-spa-friendly post themes and prompts — stop staring at a blank grid; follow the calendar and adapt to your brand.",
  "facial-anatomy-nurse-injector":
    "The anatomy guide injectors actually use — danger zones, depth, and vectors with Danielle's clinical voice. Top pick for new and returning injectors.",
  "npa-49-star-system":
    "Danielle's real 4.9-star playbook — review asks, bad-review protocol, HIPAA-safe responses, fake-review fights, and a 30-day sprint. Built from 10+ years on Google.",
  "botox-social-bundle": "Scroll-ready Botox and neurotoxin posts — stop guessing what to say in the feed.",
  "filler-social-bundle": "Filler-focused social templates patients actually engage with.",
  "filler-consent-bundle": "Full filler documentation set — consultation through photo release.",
  "chemical-peel-consent-bundle": "Every peel consent and charting step in one bundle.",
  "microneedling-consent-bundle": "Microneedling + RF paperwork ready for your chart.",
  "medspa-promo-pack": "Promos and campaigns you can run this month.",
  "myths-facts-injectors": "Educational myth-bust posts that build trust before they book.",
  "new-patient-membership-pack": "Membership and loyalty messaging for recurring revenue.",
  "review-testimonial-pack": "Make it easy for happy patients to show social proof.",
  "seasonal-marketing-pack": "Timely campaigns without starting from zero.",
  "iv-story-templates": "IV and drip story frames for busy infusion schedules.",
  "glp1-story-templates": "GLP-1 and weight-loss story content that stays compliant.",
  "weight-loss-kit": "Weight program forms and education in one download.",
  "iv-therapy-social-kit": "Large IV social library for feeds, stories, and promos.",
  "peptide-patient-guide": "Patient-facing peptide education you can brand.",
  "peptide-canva-marketing-pack":
    "Flyers, catalog, and label layouts in Canva — one pack for peptide programs that want Etsy-style polish without a designer on every asset.",
  "lash-aftercare-kit": "Aftercare cards and instructions lash clients follow.",
  "medspa-startup-checklist": "Open or level up without missing a compliance step.",
};
