/**
 * Publish a product to Etsy as a draft listing using pipeline build output.
 *
 * Usage: tsx scripts/products/publish-etsy.ts <slug>
 *        pnpm product:publish-etsy <slug>
 *
 * Reads output/{slug}/listing.json (generated by product:build).
 * Creates an Etsy draft listing and saves the result to output/{slug}/etsy-draft.json.
 *
 * This is the downstream Etsy channel — /shop is the primary storefront.
 */
import fs from "fs";
import path from "path";
import { loadEnvLocal } from "./load-env";

loadEnvLocal();

async function main() {
  const slug = process.argv[2];
  if (!slug) {
    console.error("Usage: pnpm product:publish-etsy <slug>");
    process.exit(1);
  }

  const outputDir =
    process.env.PRODUCT_OUTPUT_DIR || path.join(process.cwd(), "output");
  const listingPath = path.join(outputDir, slug, "listing.json");

  if (!fs.existsSync(listingPath)) {
    console.error(
      `No listing.json found at ${listingPath}.\n` +
        `Run 'pnpm product:build ${slug}' first to generate pipeline output.`,
    );
    process.exit(1);
  }

  const listing = JSON.parse(fs.readFileSync(listingPath, "utf8")) as Record<
    string,
    unknown
  >;

  console.log(`[publish-etsy] Product: ${listing.title}`);
  console.log(`[publish-etsy] Source: ${listingPath}`);
  console.log(`[publish-etsy] Channel: Etsy (secondary — /shop is primary)\n`);

  const { tryLoadEtsyCredsFromDb } = await import(
    "../../src/lib/integrations/etsy/etsy.service"
  );
  const dbCreds = await tryLoadEtsyCredsFromDb();
  if (dbCreds?.accessToken && !process.env.ETSY_ACCESS_TOKEN) {
    process.env.ETSY_ACCESS_TOKEN = dbCreds.accessToken;
    console.log("[publish-etsy] Loaded ETSY_ACCESS_TOKEN from database");
  }
  if (dbCreds?.shopId && !process.env.ETSY_SHOP_ID) {
    process.env.ETSY_SHOP_ID = dbCreds.shopId;
    console.log("[publish-etsy] Loaded ETSY_SHOP_ID from database");
  }

  const { EtsyService } = await import(
    "../../src/lib/integrations/etsy/etsy.service"
  );

  let etsy: InstanceType<typeof EtsyService>;
  try {
    etsy = new EtsyService();
  } catch (e) {
    console.error(
      `[publish-etsy] ${e instanceof Error ? e.message : e}`,
    );
    console.error(
      "\nEtsy credentials required. Set ETSY_ACCESS_TOKEN, ETSY_API_KEYSTRING,",
      "ETSY_API_SHARED_SECRET, ETSY_SHOP_ID in .env.local or complete OAuth.",
    );
    process.exit(1);
  }

  const result = await etsy.createDraftListing({
    title: listing.title as string,
    description: listing.description as string,
    price: (listing.price as number) || 27,
    quantity: (listing.quantity as number) || 999,
    tags: listing.tags as string[],
    taxonomyId: (listing.taxonomy_id as number) || 2078,
    isDigital: true,
  });

  if (result.ok) {
    console.log(`\n[publish-etsy] Draft listing created successfully`);
    console.log(`  Listing ID: ${result.listingId}`);
    console.log(`  State: ${result.state}`);
    console.log(`  URL: ${result.url}`);

    const resultPath = path.join(outputDir, slug, "etsy-draft.json");
    fs.writeFileSync(
      resultPath,
      JSON.stringify(
        {
          ...result,
          slug,
          source: "pipeline",
          channel: "etsy-secondary",
          primaryChannel: "/shop",
          createdAt: new Date().toISOString(),
        },
        null,
        2,
      ) + "\n",
    );
    console.log(`  Saved: ${resultPath}`);
  } else {
    console.error(`\n[publish-etsy] Failed to create draft listing`);
    console.error(`  Error: ${result.error}`);
    console.error(
      "\nNote: Build artifacts in output/ are preserved. Fix credentials and retry.",
    );
    process.exit(2);
  }
}

main().catch((e) => {
  console.error(e);
  process.exit(1);
});
